routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('homeuser', 'HomeController@index1')->name('homeuser1');

Route::resource('questions', 'QuestionsController');

Route::group(['prefix' => 'questions/{question}'], function () {
    Route::post('vote/{vote}', 'QuestionsController@vote')->name('questions.vote');
    Route::resource('answers', 'AnswersController');
    Route::resource('comments', 'QCommentsController', ['as' => 'question']);

    Route::group(['prefix' => 'answers/{answer}'], function () {
        Route::post('accept', 'AnswersController@accept')->name('answers.accept');
        Route::post('vote/{vote}', 'AnswersController@vote')->name('answers.vote');
        Route::resource('comments', 'ACommentsController', ['as' => 'answer']);
    });
});

app/Http/Controllers/QCommentsController.php
<?php

namespace App\Http\Controllers;

use App\Model\QComment;
use Auth;
use Illuminate\Http\Request;

class QCommentsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index', 'show');
    }
    
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $qcomments = QComment::where('answer', 'LIKE', "%$keyword%")
                ->latest()->paginate($perPage);
        } else {
            $qcomments = QComment::latest()->paginate($perPage);
        }

        return view('q-comments.index', compact('qcomments'));
    }

    public function create($questionId)
    {
        return view('q-comments.create', compact('questionId'));
    }

    public function store(Request $request, $questionId)
    {
        $comment = new QComment();
        $comment->user_id = Auth::user()->id;
        $comment->question_id = $questionId;
        $comment->comment = $request->comment;
        $comment->save();
        
        return redirect()
            ->route('questions.edit', $questionId)
            ->with('flash_message', 'Comment added!');
    }

    public function show($questionId, $commentId)
    {
        $comment = QComment::findOrFail($commentId);

        return view('q-comments.show', compact('comment'));
    }

    public function edit($questionId, $commentId)
    {
        $comment = QComment::findOrFail($commentId);

        return view('q-comments.edit', compact('questionId', 'comment'));
    }

    public function update(Request $request, $questionId, $commentId)
    {
        $comment = QComment::findOrFail($commentId);
        $comment->comment = $request->comment;
        $comment->update();

        return redirect()
            ->route('questions.show', $questionId)
            ->with('flash_message', 'Comment updated!');
    }

    public function destroy($questionId, $commentId)
    {
        QComment::destroy($commentId);

        return redirect()
            ->route('questions.show', $questionId)
            ->with('flash_message', 'Comment deleted!');
    }
}

resources/views/q-comments/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Create New QComment</div>
                    <div class="card-body">
                        <a href="{{ URL::previous() }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ route('question.comments.store', $questionId) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('q-comments.form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/q-comments/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Edit QComment #{{ $comment->id }}</div>
                    <div class="card-body">
                        <a href="{{ URL::previous() }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ route('question.comments.update', ['question' => $questionId, 'comment' => $comment->id]) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('q-comments.form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/q-comments/form.blade.php
<div class="form-group {{ $errors->has('comment') ? 'has-error' : ''}}">
    <label for="comment" class="control-label">{{ 'Comment' }}</label>
    <textarea class="form-control" rows="5" name="comment" type="textarea" id="comment" >{{ isset($comment->comment) ? $comment->comment : ''}}</textarea>
    {!! $errors->first('comment', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
    <input class="btn btn-primary" type="submit" value="{{ $formMode === 'edit' ? 'Update' : 'Create' }}">
</div>

resources/views/q-comments/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Qcomments</div>
                    <div class="card-body">
                        <a href="{{ url('/q-comments/create') }}" class="btn btn-success btn-sm" title="Add New QComment">
                            <i class="fa fa-plus" aria-hidden="true"></i> Add New
                        </a>

                        <form method="GET" action="{{ url('/q-comments') }}" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                <span class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>

                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th><th>Answer</th><th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($qcomments as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->answer }}</td>
                                        <td>
                                            <a href="{{ url('/q-comments/' . $item->id) }}" title="View QComment"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> View</button></a>
                                            <a href="{{ url('/q-comments/' . $item->id . '/edit') }}" title="Edit QComment"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                                            <form method="POST" action="{{ url('/q-comments' . '/' . $item->id) }}" accept-charset="UTF-8" style="display:inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete QComment" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! $qcomments->appends(['search' => Request::get('search')])->render() !!} </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/q-comments/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Comment {{ $comment->id }}</div>
                    <div class="card-body">

                        <a href="{{ URL::previous() }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <a href="{{ url('/q-comments/' . $comment->id . '/edit') }}" title="Edit Comment"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                        <form method="POST" action="{{ url('comments' . '/' . $comment->id) }}" accept-charset="UTF-8" style="display:inline">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger btn-sm" title="Delete Comment" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                        </form>
                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $comment->id }}</td>
                                    </tr>
                                    <tr><th> Answer </th><td> {{ $comment->answer }} </td></tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection