routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('homeuser', 'HomeController@index1')->name('homeuser1');

Route::resource('questions', 'QuestionsController');

Route::group(['prefix' => 'questions/{question}'], function () {
    Route::post('vote/{vote}', 'QuestionsController@vote')->name('questions.vote');
    Route::resource('answers', 'AnswersController');
    Route::resource('comments', 'QCommentsController', ['as' => 'question']);

    Route::group(['prefix' => 'answers/{answer}'], function () {
        Route::post('accept', 'AnswersController@accept')->name('answers.accept');
        Route::post('vote/{vote}', 'AnswersController@vote')->name('answers.vote');
        Route::resource('comments', 'ACommentsController', ['as' => 'answer']);
    });
});

resources/views/admin/footer.blade.php
<footer id="footer" class="site-footer js-footer" role="contentinfo">
        <div class="site-footer--container">
                <div class="site-footer--logo">

                    
                    <a href="https://stackoverflow.com"><svg aria-hidden="true" class="svg-icon native iconLogoGlyphMd" width="32" height="37" viewBox="0 0 32 37"><path d="M26 33v-9h4v13H0V24h4v9h22z" fill="#BCBBBB"/><path d="M21.5 0l-2.7 2 9.9 13.3 2.7-2L21.5 0zM26 18.4L13.3 7.8l2.1-2.5 12.7 10.6-2.1 2.5zM9.1 15.2l15 7 1.4-3-15-7-1.4 3zm14 10.79l.68-2.95-16.1-3.35L7 23l16.1 2.99zM23 30H7v-3h16v3z" fill="#F48024"/></svg></a>
                </div>
            
            <nav class="site-footer--nav">
                    <div class="site-footer--col site-footer--col__visible js-footer-col" data-name="default">
                        <h5 class="-title"><a href="https://stackoverflow.com" class="js-gps-track" data-gps-track="footer.click({ location: 2, link: 15})">Stack Overflow</a></h5>
                        <ul class="-list js-primary-footer-links">
                            <li class="-item"><a href="/questions" class="js-gps-track -link" data-gps-track="footer.click({ location: 2, link: 16})">Questions</a></li>
                                <li class="-item"><a href="https://stackoverflow.com/jobs" class="js-gps-track -link" data-gps-track="footer.click({ location: 2, link: 17})">Jobs</a></li>
                                <li class="-item"><a href="https://stackoverflow.com/jobs/directory/developer-jobs" class="js-gps-track -link" data-gps-track="footer.click({ location: 2, link: 11})">Developer Jobs Directory</a></li>
                                     <li class="-item"><a href="https://stackoverflow.com/jobs/salary" class="js-gps-track -link" data-gps-track="footer.click({ location: 2, link: 28})">Salary Calculator</a></li>
                                                            <li class="-item"><a href="/help" class="js-gps-track -link" data-gps-track="footer.click({ location: 2, link: 3 })">Help</a></li>
                                <li class="-item"><a onclick='StackExchange.switchMobile("on")' class="js-gps-track -link" data-gps-track="footer.click({ location: 2, link: 12 })">Mobile</a></li>
                        </ul>
                    </div>
            </nav>
        </div>
            </footer>

resources/views/admin/header.blade.php
<header class="top-bar js-top-bar top-bar__network _fixed">
    <div class="wmx12 mx-auto grid ai-center h100" role="menubar">
        <div class="-main grid--cell">
                <a href="#" class="left-sidebar-toggle p0 ai-center jc-center js-left-sidebar-toggle" role="menuitem" aria-haspopup="true" aria-controls="left-sidebar" aria-expanded="false"><span class="ps-relative"></span></a>
                <div class="topbar-dialog leftnav-dialog js-leftnav-dialog dno">
                    <div class="left-sidebar js-unpinned-left-sidebar" data-can-be="left-sidebar" data-is-here-when="sm"></div>
                </div>
                                <a href="{{route('questions.create')}}" class="-logo js-gps-track"
                        data-gps-track="top_nav.click({is_current:false, location:5, destination:8})">
                        <span class="-img _glyph">Stack Overflow</span>
                    </a>
        </div>
        <ol class="overflow-x-auto ml-auto -secondary grid ai-center list-reset h100 user-logged-out" role="presentation">
                <li class="-item searchbar-trigger"><a href="#" class="-link js-searchbar-trigger" role="button" aria-label="Search" aria-haspopup="true" aria-controls="search" title="Click to show search"><svg aria-hidden="true" class="svg-icon iconSearch" width="18" height="18" viewBox="0 0 18 18"><path d="M18 16.5l-5.14-5.18h-.35a7 7 0 1 0-1.19 1.19v.35L16.5 18l1.5-1.5zM12 7A5 5 0 1 1 2 7a5 5 0 0 1 10 0z"/></svg></a></li>
                
    

                @if(Auth::check())
   
                    
                    <li>
                            <a onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                    <i class="fa fa-sign-out fa-fw"></i> Logout</a>
                                     
                        </li>

                     <form id="logout-form" action="{{ route('logout')}} " method="post" style="display: none;">
                                          @csrf
                    </form>
@else
    <li class="grid--cell md:d-none">
                        <a href="{{route('register')}}" class="-marketing-link js-gps-track"
                           data-gps-track="top_nav.products.click({location:5, destination:7})"
                            >Register</a>

                            <a href="{{route('login')}}" class="-marketing-link js-gps-track"
                           data-gps-track="top_nav.products.click({location:5, destination:7})"
                            >Login</a>
                    </li>
@endif



                    
            <li class="js-topbar-dialog-corral" role="presentation">

            </li>
        </ol>

    </div>
</header>

resources/views/admin/navkiri.blade.php
<li>
    <ol class="nav-links">
                            <li class="fs-fine tt-uppercase ml8 mt16 mb4 fc-light">Project Sanbernine</li>
    @if(Auth::check())

<li class=" youarehere">
       
        <a id="nav-questions"
            href="{{route('questions.index')}}"
            class="pl8 js-gps-track nav-links--link -link__with-icon"
            data-gps-track="top_nav.click({is_current:true, location:5, destination:1})">
            <svg aria-hidden="true" class="svg-icon iconGlobe" width="18" height="18" viewBox="0 0 18 18"><path d="M9 1a8 8 0 1 0 0 16A8 8 0 0 0 9 1zM8 15.32a6.4 6.4 0 0 1-5.23-7.75L7 11.68v.8c0 .88.12 1.32 1 1.32v1.52zm5.72-2c-.2-.66-1-1.32-1.72-1.32h-1v-2c0-.44-.56-1-1-1H6V7h1c.44 0 1-.56 1-1V5h2c.88 0 1.4-.72 1.4-1.6v-.33a6.4 6.4 0 0 1 2.32 10.24v.01z"/></svg>                <span class="-link--channel-name">Dashboard</span>
        </a>
    </li>

    <li>
        <a id="nav-tags"
            href="{{route('questions.create')}}" class=" js-gps-track nav-links--link" data-gps-track="top_nav.click({is_current:false, location:5, destination:2})">Create
        </a>
    </li>
    <li>
        <a id="nav-tags"
            href="{{route('questions.create')}}" class=" js-gps-track nav-links--link" data-gps-track="top_nav.click({is_current:false, location:5, destination:2})">Home
        </a>
    </li>
                    
@else
 <li class=" youarehere">
       
        <a id="nav-questions"
            href="{{route('questions.index')}}"
            class="pl8 js-gps-track nav-links--link -link__with-icon"
            data-gps-track="top_nav.click({is_current:true, location:5, destination:1})">
            <svg aria-hidden="true" class="svg-icon iconGlobe" width="18" height="18" viewBox="0 0 18 18"><path d="M9 1a8 8 0 1 0 0 16A8 8 0 0 0 9 1zM8 15.32a6.4 6.4 0 0 1-5.23-7.75L7 11.68v.8c0 .88.12 1.32 1 1.32v1.52zm5.72-2c-.2-.66-1-1.32-1.72-1.32h-1v-2c0-.44-.56-1-1-1H6V7h1c.44 0 1-.56 1-1V5h2c.88 0 1.4-.72 1.4-1.6v-.33a6.4 6.4 0 0 1 2.32 10.24v.01z"/></svg>                <span class="-link--channel-name">Dashboard</span>
        </a>
    </li>

    <li>
        <a id="nav-tags"
            href="{{route('questions.create')}}" class=" js-gps-track nav-links--link" data-gps-track="top_nav.click({is_current:false, location:5, destination:2})">Create
        </a>
    </li>  
@endif

    </ol>
</li>

resources/views/admin/sidebar.blade.php
<div class="col-md-3">
    <div class="card">
        <div class="card-header">
            Sidebar
        </div>

        <div class="card-body">
            <ul class="nav" role="tablist">
                <li role="presentation">
                    <a href="{{ route('questions.index') }}">
                        Question
                    </a>
                </li>
            </ul>
        </div>

        <div class="card-body">
            <ul class="nav" role="tablist">
                <li role="presentation">
                    <a href="{{ route('answers.index', 1) }}">
                        Answer
                    </a>
                </li>
            </ul>
        </div>

        <div class="card-body">
            <ul class="nav" role="tablist">
                <li role="presentation">
                    <a href="{{ route('question.comments.index', 1) }}">
                        Q Comment
                    </a>
                </li>
            </ul>
        </div>

        <div class="card-body">
            <ul class="nav" role="tablist">
                <li role="presentation">
                    <a href="{{ route('answer.comments.index', ['question' => 1, 'answer' => 1]) }}">
                        A Comment
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>