routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('homeuser', 'HomeController@index1')->name('homeuser1');

Route::resource('questions', 'QuestionsController');

Route::group(['prefix' => 'questions/{question}'], function () {
    Route::post('vote/{vote}', 'QuestionsController@vote')->name('questions.vote');
    Route::resource('answers', 'AnswersController');
    Route::resource('comments', 'QCommentsController', ['as' => 'question']);

    Route::group(['prefix' => 'answers/{answer}'], function () {
        Route::post('accept', 'AnswersController@accept')->name('answers.accept');
        Route::post('vote/{vote}', 'AnswersController@vote')->name('answers.vote');
        Route::resource('comments', 'ACommentsController', ['as' => 'answer']);
    });
});

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Model\AComment;
use App\Model\Answer;
use Auth;
use Illuminate\Http\Request;

class AnswersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index', 'show');
    }
    
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $answers = Answer::where('answer', 'LIKE', "%$keyword%")
                ->latest()->paginate($perPage);
        } else {
            $answers = Answer::latest()->paginate($perPage);
        }

        return view('answers.index', compact('answers'));
    }

    public function create($questionId)
    {
        return view('answers.create', compact('questionId'));
    }

    public function store(Request $request, $questionId)
    {
        $answer = new Answer();
        $answer->user_id = Auth::user()->id;
        $answer->question_id = $questionId;
        $answer->answer = $request->answer;
        $answer->save();
        
        return redirect()
            ->route('questions.edit', $questionId)
            ->with('flash_message', 'Answer added!');
    }

    public function show($questionId, $answerId)
    {
        $answer = Answer::findOrFail($answerId);

        $perPage = 25;
     
        $acomments = AComment::where('answer_id', $answerId)
            ->latest()->paginate($perPage);

        return view('answers.show', compact('questionId', 'answer', 'acomments'));
    }

    public function edit($questionId, $answerId)
    {
        $answer = Answer::findOrFail($answerId);

        return view('answers.edit', compact('questionId', 'answer'));
    }

    public function update(Request $request, $questionId, $answerId)
    {
        $requestData = $request->all();
        
        $answer = Answer::findOrFail($answerId);
        $answer->update($requestData);

        return redirect()
            ->route('questions.show', $questionId)
            ->with('flash_message', 'Answer updated!');
    }

    public function accept($questionId, $answerId)
    {
        $answers = Answer::where('question_id', $questionId)->get();

        foreach($answers as $answer) {
            $answer->is_accepted = false;
            $answer->update();
        }

        $answer = Answer::findOrFail($answerId);
        $answer->is_accepted = true;
        $answer->update();

        return redirect()
            ->back()
            ->with('flash_message', 'Answer updated!');
    }

    public function vote($questionId, $answerId, $vote)
    {
        $answer = Answer::findOrFail($answerId);
        $answer->votes()->sync([Auth::user()->id => ['vote' => $vote]]);

        return back()->with('flash_message', 'Rate applied!');
    }

    public function destroy($questionId, $answerId)
    {
        Answer::destroy($answerId);

        return back()->with('flash_message', 'Answer deleted!');
    }
}

resources/views/answers/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Create New Answer</div>
                    <div class="card-body">
                        <a href="{{ URL::previous() }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ route('answers.store', $questionId) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('answers.form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Edit Answer #{{ $answer->id }}</div>
                    <div class="card-body">
                        <a href="{{ URL::previous() }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ route('answers.update', ['question' => $questionId, 'answer' => $answer->id]) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('answers.form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/answers/form.blade.php
<div class="form-group {{ $errors->has('answer') ? 'has-error' : ''}}">
    <label for="answer" class="control-label">{{ 'Answer' }}</label>
    <textarea class="form-control" rows="5" name="answer" type="textarea" id="answer" >{{ isset($answer->answer) ? $answer->answer : ''}}</textarea>
    {!! $errors->first('answer', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
    <input class="btn btn-primary" type="submit" value="{{ $formMode === 'edit' ? 'Update' : 'Create' }}">
</div>

resources/views/answers/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Answers</div>
                    <div class="card-body">
                        <a href="{{ url('/answers/create') }}" class="btn btn-success btn-sm" title="Add New Answer">
                            <i class="fa fa-plus" aria-hidden="true"></i> Add New
                        </a>

                        <form method="GET" action="{{ url('/answers') }}" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request('search') }}">
                                <span class="input-group-append">
                                    <button class="btn btn-secondary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>

                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th><th>Answer</th><th>Is Accepted</th><th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($answers as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->answer }}</td><td>{{ $item->is_accepted }}</td>
                                        <td>
                                            <a href="{{ url('/answers/' . $item->id) }}" title="View Answer"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> View</button></a>
                                            <a href="{{ url('/answers/' . $item->id . '/edit') }}" title="Edit Answer"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                                            <form method="POST" action="{{ url('/answers' . '/' . $item->id) }}" accept-charset="UTF-8" style="display:inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete Answer" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! $answers->appends(['search' => Request::get('search')])->render() !!} </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/answers/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Answer {{ $answer->id }}</div>
                    <div class="card-body">

                        <a href="{{ URL::previous() }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <a href="{{ url('/answers/' . $answer->id . '/edit') }}" title="Edit Answer"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                        <form method="POST" action="{{ url('answers' . '/' . $answer->id) }}" accept-charset="UTF-8" style="display:inline">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger btn-sm" title="Delete Answer" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                        </form>
                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $answer->id }}</td>
                                    </tr>
                                    <tr><th> Answer </th><td> {{ $answer->answer }} </td></tr><tr><th> Is Accepted </th><td> {{ $answer->is_accepted }} </td></tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
                <div class="card">
                    <div class="card-header">Acomments</div>
                    <div class="card-body">
                        <a href="{{ route('answer.comments.create', ['question' => $questionId, 'answer' => $answer->id]) }}" class="btn btn-success btn-sm" title="Add New AComment">
                            <i class="fa fa-plus" aria-hidden="true"></i> Add New
                        </a>
                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th><th>Comment</th><th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($acomments as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->comment }}</td>
                                        <td>
                                            <a href="{{ route('answer.comments.show', ['question' => $questionId, 'answer' => $answer->id, 'comment' => $item->id]) }}" title="View AComment"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> View</button></a>
                                            <a href="{{ route('answer.comments.edit', ['question' => $questionId, 'answer' => $answer->id, 'comment' => $item->id]) }}" title="Edit AComment"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                                            <form method="POST" action="{{ route('answer.comments.destroy', ['question' => $questionId, 'answer' => $answer->id, 'comment' => $item->id]) }}" accept-charset="UTF-8" style="display:inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete AComment" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! $acomments->appends(['search' => Request::get('search')])->render() !!} </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection