routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('home', 'HomeController@index')->name('home');
Route::get('homeuser', 'HomeController@index1')->name('homeuser1');

Route::resource('questions', 'QuestionsController');

Route::group(['prefix' => 'questions/{question}'], function () {
    Route::post('vote/{vote}', 'QuestionsController@vote')->name('questions.vote');
    Route::resource('answers', 'AnswersController');
    Route::resource('comments', 'QCommentsController', ['as' => 'question']);

    Route::group(['prefix' => 'answers/{answer}'], function () {
        Route::post('accept', 'AnswersController@accept')->name('answers.accept');
        Route::post('vote/{vote}', 'AnswersController@vote')->name('answers.vote');
        Route::resource('comments', 'ACommentsController', ['as' => 'answer']);
    });
});

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Model\Answer;
use App\Model\QComment;
use App\Model\AComment;
use App\Model\Question;
use App\Model\Tag;
use Auth;
use Illuminate\Http\Request;

class QuestionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index', 'show', 'edit');
    }
    
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $questions = Question::where('title', 'LIKE', "%$keyword%")
                ->orWhere('question', 'LIKE', "%$keyword%")
                ->latest()->paginate($perPage);
        } else {
            $questions = Question::latest()->paginate($perPage);
        }

        return view('questions.index', compact('questions'));
    }

    public function create()
    {
        return view('questions.create');
    }

    public function store(Request $request)
    {
        $question = new Question();
        $question->user_id = Auth::user()->id;
        $question->title = $request->title;
        $question->question = $request->question;
        $question->save();

        $requestTags = explode(",", $request->tags);

        foreach($requestTags as $requestTag) {
            $tag = Tag::firstOrCreate(['tag' => $requestTag]);
            $question->tags()->attach($tag->id);
        }
        
        return redirect()
            ->route('questions.index')
            ->with("berhasil","Kamu Berhasil Menambah");

    }

    public function show($questionId)
    {
        $question = Question::findOrFail($questionId);

        $perPage = 25;

        $answers = Answer::where('question_id', $questionId)
            ->latest()->paginate($perPage);
     
        $qcomments = QComment::where('question_id', $questionId)
            ->latest()->paginate($perPage);

        $acomments = AComment::where('question_id', $questionId)
            ->latest()->paginate($perPage);
        return view('questions.show', compact('question', 'answers', 'qcomments'));
    }

    public function edit($id)
    {
        $question = Question::findOrFail($id);

        $tags = array();

        foreach ($question->tags as $tag) {
            $tags[] = $tag->tag;
        }

        $question->tags = implode(',', $tags);

        $perPage = 25;

        $answers = Answer::where('question_id', $id)
            ->latest()->paginate($perPage);
     
        $qcomments = QComment::where('question_id', $id)
            ->latest()->paginate($perPage);

        return view('questions.edit', compact('question', 'answers', 'qcomments'));
    }

    public function update(Request $request, $id)
    {
        $requestData = $request->all();
        
        $question = Question::findOrFail($id);
        $question->update($requestData);

        return redirect('questions')->with('flash_message', 'Question updated!');
    }

    public function vote($id, $vote)
    {
        $question = Question::findOrFail($id);
        $question->votes()->sync([Auth::user()->id => ['vote' => $vote]]);

        return back()->with('flash_message', 'Rate applied!');
    }

    public function destroy($id)
    {
        Question::destroy($id);

        return redirect('questions')->with('flash_message', 'Question deleted!');
    }
}

resources/views/questions/create1.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Create New Question</div>
                    <div class="card-body">
                        <a href="{{ url('/questions') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        <form method="POST" action="{{ url('/questions') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('questions.form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/form.blade.php
@push('style')
    <link href="{{ asset('css/simplemde.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap-tagsinput.css') }}" rel="stylesheet">
@endpush

<div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
    <label for="title" class="control-label">{{ 'Title' }}</label>
    <input class="form-control" name="title" type="text" id="title" value="{{ isset($question->title) ? $question->title : ''}}" >
    {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {{ $errors->has('question') ? 'has-error' : ''}}">
    <label for="question" class="control-label">{{ 'Question' }}</label>
    <textarea class="form-control" rows="5" name="question" type="textarea" id="question" >{{ isset($question->question) ? $question->question : ''}}</textarea>
    {!! $errors->first('question', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {{ $errors->has('tags') ? 'has-error' : ''}}">
    <label for="tags" class="control-label">{{ 'Tags' }}</label>
    <input class="form-control" name="tags" type="text" id="tags" value="{{ isset($question->tags) ? $question->tags : ''}}" data-role="tagsinput">
    {!! $errors->first('tags', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
    <input class="btn btn-primary" type="submit" value="{{ $formMode === 'edit' ? 'Update' : 'Create' }}">
</div>

@push('scripts')
    <script src="{{ asset('js/simplemde.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-tagsinput.min.js') }}"></script>

    <script>
        var simplemde = new SimpleMDE({ element: document.getElementById("question") });
    </script>
@endpush

resources/views/questions/home.blade.php
@extends('layouts.coba')

@section('content')
<div id="qlist-wrapper" class="flush-left">
    <div id="question-mini-list">
        <div>

<div class="question-summary narrow"
     id="question-summary-60443262">
    <div onclick="window.location.href='/questions/60443262/trying-to-use-cyl-bessel-i-from-std-c'" class="cp">
        <div class="votes">
            <div class="mini-counts"><span title="0 votes">0</span></div>
            <div>votes</div>
        </div>
        <div class="status unanswered">
            <div class="mini-counts"><span title="0 answers">0</span></div>
            <div>answers</div>
        </div>
        <div class="views">
            <div class="mini-counts"><span title="6 views">6</span></div>
            <div>views</div>
        </div>
    </div>
    <div class="summary">
        
        
        <h3><a href="/questions/60443262/trying-to-use-cyl-bessel-i-from-std-c" class="question-hyperlink">Trying to use &#39;cyl_bessel_i&#39; from STD C++</a></h3>
        <div class="tags t-c&#231;&#231; t-c&#231;&#231;17">
            <a href="/questions/tagged/c%2b%2b" class="post-tag" title="show questions tagged &#39;c++&#39;" rel="tag">c++</a> <a href="/questions/tagged/c%2b%2b17" class="post-tag" title="show questions tagged &#39;c++17&#39;" rel="tag">c++17</a> 
        </div>
        <div class="started">
            <a href="/questions/60443262/trying-to-use-cyl-bessel-i-from-std-c" class="started-link">modified <span title="2020-02-27 23:52:36Z" class="relativetime">1 min ago</span></a>
            <a href="/users/1427563/jla">jla</a> <span class="reputation-score" title="reputation score " dir="ltr">2,281</span>
        </div>
    </div>
</div>

  </div>
    </div>
</div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.coba')


@section('content')

@foreach($questions as $key => $question)
<div class="question-summary" id="question-summary-60427542">
    <div class="statscontainer">
        <div class="stats">
            <div class="vote">
                <div class="votes">
                    <span class="vote-count-post "><strong>-1</strong></span>
                    <div class="viewcount">votes</div>
                </div>
            </div>
            <!-- answer -->
            <div class="status answered">
                <strong>2</strong>answers
            </div>
            <!-- answer -->
        </div>
<!-- view -->
<div class="views " title="20 views">
    20 views
</div>
<!-- /view -->
    </div>

    <div class="summary">
        <!-- judul dan kelink -->
        <h3><a href="{{ route('questions.edit', $question->id) }}" class="question-hyperlink">{{$question->title}}</a></h3>
        <!-- /judul kelink -->

            <!-- isi  -->
        <div class="excerpt">
            {{$question->question}}
        </div>
        <!-- /isi -->

        <!-- tampil tag rooting berdasarkan tags dari id_pertanyaan -->
        <div class="tags t-php t-laravel t-pdf t-pdf-viewer">
            <a href="{{$question->tags}}" class="post-tag" title="show questions tagged &#39;php&#39;" rel="tag">
                {{$question->tags}}
            </a>  
        </div>
        <!-- tampil tag rooting -->

        <div class="started fr">
            <div class="user-info ">
    <div class="user-action-time">
        Created at <span title="{{$question->question}}" class="relativetime">{{$question->created_at}}</span>
    </div>
    <div class="user-gravatar32">
        <a href="/users/10451451/mahesh-kalasa"><div class="gravatar-wrapper-32"><img src="https://lh4.googleusercontent.com/-TKnIY3SMzpc/AAAAAAAAAAI/AAAAAAAABmM/-Ne9MPmUKtQ/photo.jpg?sz=32" alt="" width="32" height="32" class="bar-sm"></div></a>
    </div>
    <div class="user-details">
        <a href="">{{$question->user_id}}</a>
        <div class="-flair">
            <span class="reputation-score" title="reputation score " dir="ltr">1</span>
        </div>
    </div>
</div>
        </div>
    </div>


</div>
@endforeach
@endsection

<script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
                responsive: true
        });
    });

/*@if (session("berhasil")) {}*/
    Swal.fire({
        title: 'Berhasil!',
        // text: "{{session('berhasil')}}",
        text: 'berhasil',
        icon: 'success',
        confirmButtonText: 'Cool'
    })
/*@endif*/
</script>

<div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Question {{ $question->id }}</div>
                    <div class="card-body">

                        <a href="{{ route('questions.index') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <a href="{{ route('questions.edit', $question->id) }}" title="Edit Question"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                        <form method="POST" action="{{ route('questions.destroy', $question->id) }}" accept-charset="UTF-8" style="display:inline">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                        <button type="submit" class="btn btn-danger btn-sm" title="Delete Question" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                        </form>
                        <br/>
                        <br/>

                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th><td>{{ $question->id }}</td>
                                    </tr>
                                    <tr>
                                        <th> Title </th><td> {{ $question->title }} </td>
                                    </tr>
                                    <tr>
                                        <th> Question </th><td> {{ $question->question }} </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <form method="POST" action="{{ route('questions.vote', ['question' => $question->id, 'vote' => 'up']) }}" accept-charset="UTF-8" style="display:inline">
                            @csrf
                            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-trash-o" aria-hidden="true"></i> Vote Up</button>
                        </form>

                        <form method="POST" action="{{ route('questions.vote', ['question' => $question->id, 'vote' => 'down']) }}" accept-charset="UTF-8" style="display:inline">
                            @csrf
                            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-trash-o" aria-hidden="true"></i> Vote Down</button>
                        </form>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">Qcomments</div>
                    <div class="card-body">
                        <a href="{{ route('question.comments.create', $question->id) }}" class="btn btn-success btn-sm" title="Add New QComment">
                            <i class="fa fa-plus" aria-hidden="true"></i> Add New
                        </a>
                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th><th>Comment</th><th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($qcomments as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->comment }}</td>
                                        <td>
                                            <a href="{{ route('question.comments.show', ['question' => $question->id, 'comment' => $item->id]) }}" title="View QComment"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> View</button></a>
                                            <a href="{{ route('question.comments.edit', ['question' => $question->id, 'comment' => $item->id]) }}" title="Edit QComment"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                                            <form method="POST" action="{{ route('question.comments.destroy', ['question' => $question->id, 'comment' => $item->id]) }}" accept-charset="UTF-8" style="display:inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete QComment" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! $qcomments->appends(['search' => Request::get('search')])->render() !!} </div>
                        </div>

                    </div>
                </div>
                <div class="card">
                    <div class="card-header">Answers</div>
                    <div class="card-body">
                        <a href="{{ route('answers.create', $question->id) }}" class="btn btn-success btn-sm" title="Add New Answer">
                            <i class="fa fa-plus" aria-hidden="true"></i> Add New
                        </a>
                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th><th>Answer</th><th>Is Accepted</th><th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($answers as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->answer }}</td><td>{{ $item->is_accepted }}</td>
                                        <td>
                                            <form method="POST" action="{{ route('answers.accept', ['question' => $question->id, 'answer' => $item->id]) }}" accept-charset="UTF-8" style="display:inline">
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-trash-o" aria-hidden="true"></i> Pilih Jawaban</button>
                                            </form>

                                            <form method="POST" action="{{ route('answers.vote', ['question' => $question->id, 'answer' => $item->id, 'vote' => 'up']) }}" accept-charset="UTF-8" style="display:inline">
                                                @csrf
                                                <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-trash-o" aria-hidden="true"></i> Vote Up</button>
                                            </form>
                    
                                            <form method="POST" action="{{ route('answers.vote', ['question' => $question->id, 'answer' => $item->id, 'vote' => 'down']) }}" accept-charset="UTF-8" style="display:inline">
                                                @csrf
                                                <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-trash-o" aria-hidden="true"></i> Vote Down</button>
                                            </form>

                                            <a href="{{ route('answers.show', ['question' => $question->id, 'answer' => $item->id]) }}" title="View Answer"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> View</button></a>
                                            
                                            <a href="{{ route('answers.edit', ['question' => $question->id, 'answer' => $item->id]) }}" title="Edit Answer"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>

                                            <form method="POST" action="{{ route('answers.destroy', ['question' => $question->id, 'answer' => $item->id]) }}" accept-charset="UTF-8" style="display:inline">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete Answer" onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! $answers->appends(['search' => Request::get('search')])->render() !!} </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection